#! /usr/bin/python3

from jinja2 import Environment, FileSystemLoader

import os
import sys

environment = Environment(loader=FileSystemLoader("template/"))


def create_file(template_file, modulename,  outname):
	template = environment.get_template(template_file)
	content = template.render(
	    name = modulename,
	)


	filename = os.path.join( modulename,outname)

	# print(modulename, filename, outname)

	with open(filename, 'w') as f:
		f.write(content)
		f.close()


def main():


	if len(sys.argv) == 1:
		print("USAGE:\n {} <module name>".format(sys.argv[0]))
		exit(1)

	modulename = sys.argv[1]
	if not os.path.isdir(modulename):
		os.mkdir(modulename, mode=0o755)
	
	create_file('Makefile', modulename, 'Makefile')
	create_file('sql--0.1.sql', modulename, modulename + "--0.1.sql")
	create_file('c.c', modulename, modulename + ".c")
	create_file('control.control', modulename, modulename + ".control")

	print( 'the module {} was autogenerated in dir {}'.format(modulename,modulename))



main()